bases:
- ../../base
namePrefix: staging-
patchesStrategicMerge:
- staging-configmap.yaml 
configMapGenerator:
- name: rsvpconfig-staging
  literals:
    - TEXT1="Welcome to"
    - TEXT2="Updated Staging"
