resources:
- ../../base
namePrefix: staging-
commonLabels:
  env: staging
patchesStrategicMerge:
- staging-configmap.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="RSVP Staging-new"
  name: rsvpconfig-staging
images:
- name: atul7cloudyuga/rsvp-demo
  newTag: 7bb7e93031b06d57212f08c89c32a93d27faa247
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
