resources:
- ../../base
namePrefix: prod-
commonLabels:
  env: prod
patchesStrategicMerge:
- staging-configmap.yaml
- replica-count.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="Production"
  name: rsvpconfig-staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: atul7cloudyuga/rsvp-demo
  newTag: 7bb7e93031b06d57212f08c89c32a93d27faa247
