resources:
- ../../base
namePrefix: prod-
patchesStrategicMerge:
- prod-configmap.yaml 
- replica-count.yaml
configMapGenerator:
- name: rsvpconfig-prod
  literals:
    - TEXT1="Welcome to"
    - TEXT2="Production"
